services:
  liteika_api:
    build: .
    container_name: liteika_api
    restart: always
    ports:
      - "8888:8000"
    env_file:
      - .env
    command: >
      uvicorn app.liteika_api.main:app
      --host 0.0.0.0
      --port 8000
      --proxy-headers
      --forwarded-allow-ips="*"
    volumes:
      - .:/app


  postgres:
    image: ankane/pgvector:latest
    container_name: pg_liteika
    restart: always
    ports:
      - "5444:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data


  migrate:
    build: .
    container_name: liteika_migrations
    command: alembic upgrade head
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: liteika_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - liteika_api
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  pgdata:
